title: Nasim's Data Science Blog
theme: jekyll-theme-slate
author: GitHub User
email: nasim.taba2@gmail.com  
description: My passion is Data Science. Here I'd like to share my learning and experiences with you.

# social links
twitter_username: Nasimtaba # DO NOT include the @ character, or else the build will fail!
github_username:  Northbreeze # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
